version: '3.7'

services: 
  django_gunicorn:  # wsgi http server (application server)
    volumes: 
      - static:/static  # connect the volume
    env_file: # variables for Django container
      - .env  # don't put it under version control! (it has some secrets/keys in it)
    build:
      context: .
    ports: 
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes: 
      - static:/static
    ports: 
      - "80:80"
    depends_on: 
      - django_gunicorn


volumes:  # volume to handel static assets  (images/css/js)
  static: